-- ═══════════════════════════════════════════════════════════════════════════════
-- Sprint 12 — Process Intelligence & Living Graph AI
-- Seed data for ProjectOps360° dogfooding
-- NOTE: The canonical seed script is scripts/seed-sprint12.js (Node.js)
-- This SQL file is a reference/mirror for manual execution via Supabase SQL Editor
-- It is idempotent: safe to re-run
-- ═══════════════════════════════════════════════════════════════════════════════

-- ── Constants ──────────────────────────────────────────────────────────────────
-- project_id: a30e3eb9-528e-46ce-b6d6-9ed80086b936  (ProjectOps360°)
-- organization_id: 4f00f16b-96d8-4fd6-9375-20e2b11564a6
-- milestone_id: a1b2c3d4-0001-4000-8000-000000000012

-- ═══════════════════════════════════════════════════════════════════════════════
-- STEP 1: Upsert Milestone
-- ═══════════════════════════════════════════════════════════════════════════════
INSERT INTO milestones (
  id, organization_id, project_id, title, description, status,
  start_date, target_date, progress_percent, order_index, icon_key
) VALUES (
  'a1b2c3d4-0001-4000-8000-000000000012',
  '4f00f16b-96d8-4fd6-9375-20e2b11564a6',
  'a30e3eb9-528e-46ce-b6d6-9ed80086b936',
  'Sprint 12 — Process Intelligence & Living Graph AI',
  'Build the Process Intelligence layer: interpret the Living Graph, explain process behavior, detect bottlenecks, identify SOP opportunities, generate retrospectives, create improvement backlog items, and convert process insights into user-approved actions.',
  'in_progress',
  '2026-06-09',
  '2026-06-27',
  0,
  120,
  'sparkles'
)
ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  status       = EXCLUDED.status,
  start_date   = EXCLUDED.start_date,
  target_date  = EXCLUDED.target_date,
  order_index  = EXCLUDED.order_index,
  icon_key     = EXCLUDED.icon_key,
  updated_at   = now();

-- ═══════════════════════════════════════════════════════════════════════════════
-- STEP 2: Upsert Tasks (PI-001 through PI-022)
-- Uses ON CONFLICT on (project_id, external_key) for idempotency
-- prompt_body maps to ai_prompt, prompt_context maps to ai_next_action
-- ═══════════════════════════════════════════════════════════════════════════════

-- PI-001: Define Living Graph Data Model (prompt_ready, p1, 6h)
INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-001', 'Define Living Graph Data Model', 'Design the entity/edge schema for the process intelligence graph. Entities represent process nodes (task transitions, decision cascades, communication flows, document links). Edges represent causal, temporal, and dependency relationships.', 'prompt_ready', 'p1', 'Sprint 12', '2026-06-09', '2026-06-11', 6, 43, 'You are a Senior Data Architect working on ProjectOps360°. Design the Living Graph data model: process_nodes, process_edges, process_snapshots tables with indexes, RLS, and backfill function.', 'Design entity/edge schema for process intelligence graph', '1) process_nodes and process_edges tables created 2) process_snapshots table 3) All indexes defined 4) RLS policies 5) Backfill function 6) Migration file ready')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

-- PI-002: Create Living Graph Supabase Migration (not_started, p1, 4h)
INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-002', 'Create Living Graph Supabase Migration', 'Apply the Living Graph migration: create process_nodes, process_edges, process_snapshots tables with indexes, RLS, triggers, and backfill seed function.', 'not_started', 'p1', 'Sprint 12', '2026-06-11', '2026-06-12', 4, 44, 'You are a Senior Supabase Engineer. Apply the Living Graph migration and execute backfill from existing project data (tasks, decisions, communications).', 'Apply migration and execute backfill from existing data', '1) Migration applied 2) Backfill completed 3) Edges populated 4) Traversal query works 5) Row counts verified')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

-- PI-003: Build Process Event Ingestion Pipeline (not_started, p1, 8h)
INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-003', 'Build Process Event Ingestion Pipeline', 'Create server actions and hooks that automatically emit graph events when existing entities change.', 'not_started', 'p1', 'Sprint 12', '2026-06-12', '2026-06-15', 8, 45, 'You are a Senior Full Stack Engineer. Build src/lib/graph/emit-event.ts with emitProcessNode, emitProcessEdge, autoLinkProcessNode. Integrate into existing server actions with fire-and-forget pattern.', 'Hook into existing server actions to emit graph events automatically', '1) emit-event.ts created 2) Integrated into actions 3) Fire-and-forget 4) TypeScript types added 5) Manual test verified')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

-- PI-004: Implement Graph Traversal & Query API (not_started, p2, 10h)
INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-004', 'Implement Graph Traversal & Query API', 'Create Supabase RPC functions for graph traversal: path finding, cycle detection, subgraph extraction, timeline queries.', 'not_started', 'p2', 'Sprint 12', '2026-06-12', '2026-06-16', 10, 46, 'You are a Senior Database Engineer. Create 5 RPC functions: find_path, detect_cycles, extract_subgraph, get_process_timeline, get_node_neighbors. SECURITY DEFINER with org membership check.', 'Create Supabase RPC functions for graph traversal, cycle detection, and subgraph extraction', '1) 5 RPC functions created 2) find_path works 3) detect_cycles works 4) extract_subgraph works 5) get_process_timeline works 6) TypeScript types added 7) Sample queries verified')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

-- PI-005: Build Living Graph Visualization Component (not_started, p2, 12h)
INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-005', 'Build Living Graph Visualization Component', 'Create an interactive React component that visualizes the Living Graph using React Flow. Support zoom, pan, click-to-inspect, filtering by node type, and time-range selection.', 'not_started', 'p2', 'Sprint 12', '2026-06-16', '2026-06-20', 12, 47, 'You are a Senior Frontend Engineer. Build living-graph-view.tsx using @xyflow/react with custom node/edge types, detail panel, filters, search, minimap. Create page route under Execution Map.', 'Build interactive graph visualization with React Flow, node/edge types, filtering, and time-range selection', '1) living-graph-view.tsx renders graph 2) Custom node types 3) Custom edge types 4) Click-to-inspect 5) Filters 6) Search 7) Page route integrated 8) i18n added')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

-- PI-006 through PI-022: abbreviated for reference — full data in scripts/seed-sprint12.js
-- The Node.js script is the canonical source for all 22 tasks with full prompt_body
-- Below are the remaining tasks with shortened SQL for manual SQL editor execution

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-006', 'Design Process Interpretation Architecture', 'Design the architecture for the Process Interpretation Engine: graph patterns, process phases, deviations, human-readable explanations.', 'not_started', 'p1', 'Sprint 12', '2026-06-09', '2026-06-10', 4, 48, 'You are a Senior Software Architect. Design the Process Interpretation Engine: data flow, core interfaces (ProcessInterpreter, PatternDetector, DeviationDetector, NarrativeGenerator), AI integration, caching.', 'Architect the interpretation engine: data flow, interfaces, AI integration, caching', '1) Architecture document 2) TypeScript interfaces 3) Core abstractions defined 4) AI integration contract 5) Caching strategy 6) API contract')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-007', 'Implement Process Timeline Reconstruction', 'Build the service that reconstructs an ordered process timeline from graph events with causal chains.', 'not_started', 'p2', 'Sprint 12', '2026-06-15', '2026-06-17', 8, 49, 'You are a Senior Full Stack Engineer. Build timeline-reconstructor.ts: reconstructTimeline(projectId) with phases, events, parallelTracks, causal predecessors/successors.', 'Reconstruct ordered process timeline from graph events with causal chains', '1) timeline-reconstructor.ts created 2) ProcessTimeline type 3) Causal chains 4) Server action 5) Tests pass')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-008', 'Build Behavior Pattern Detection', 'Implement the pattern detection service: decision sequences, task flow patterns, blocker cycles, acceleration/deceleration signals.', 'not_started', 'p2', 'Sprint 12', '2026-06-15', '2026-06-18', 10, 50, 'You are a Senior Full Stack Engineer. Build pattern-detector.ts with 5 pattern types: DecisionSequence, TaskFlowPattern, BlockerCycle, AccelerationSignal, DecelerationSignal.', 'Detect recurring process patterns: decision sequences, task flows, blocker cycles, acceleration/deceleration', '1) pattern-detector.ts 2) 5 pattern types 3) frequency/confidence/recommendation 4) Server action 5) 5-min cache')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-009', 'Create Process Interpretation API & UI Panel', 'Build server actions and UI panel for process interpretation: narrative, patterns, deviation alerts.', 'not_started', 'p2', 'Sprint 12', '2026-06-18', '2026-06-20', 8, 51, 'You are a Senior Full Stack Engineer. Create interpretProcessAction server action (OpenAI GPT-4o narrative) + interpretation-panel.tsx with narrative, patterns, deviations.', 'Expose interpretation results via server actions + build narrative UI panel', '1) Server action created 2) AI narrative generation 3) Interpretation panel 4) Page route 5) i18n 6) Integrated')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-010', 'Implement Bottleneck Detection Algorithm', 'Build bottleneck detection: wait times, stalled transitions, resource contention with impact scores and recommendations.', 'not_started', 'p1', 'Sprint 12', '2026-06-16', '2026-06-18', 8, 52, 'You are a Senior Full Stack Engineer. Build bottleneck-detector.ts with 3 types: WaitTime, StalledTransition, ResourceContention. Configurable thresholds.', 'Detect wait-time bottlenecks, stalled transitions, and resource contention in process graph', '1) bottleneck-detector.ts 2) 3 bottleneck types 3) severity/impact/recommendation 4) Configurable thresholds 5) Server action 6) TypeScript types')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-011', 'Build Bottleneck Visualization & Highlighting', 'Add bottleneck indicators to the Living Graph: severity-based styling, hover tooltips, summary panel.', 'not_started', 'p2', 'Sprint 12', '2026-06-18', '2026-06-20', 6, 53, 'You are a Senior Frontend Engineer. Extend living-graph-view.tsx with bottleneck highlighting: red/orange glow, animated edges, tooltips, bottleneck-summary.tsx, filter toggle.', 'Highlight bottleneck nodes/edges on the Living Graph with severity-based styling', '1) Severity-based colors 2) Animated edges 3) Hover tooltips 4) Summary panel 5) Filter toggle 6) i18n')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-012', 'Create Bottleneck Alerting & Recommendations', 'Build proactive bottleneck alerting and AI-powered resolution recommendations.', 'not_started', 'p3', 'Sprint 12', '2026-06-20', '2026-06-23', 8, 54, 'You are a Senior Full Stack Engineer. Build bottleneck-alerter.ts (NEW/WORSENED/RESOLVED alerts) + bottleneck-recommender.ts (OpenAI resolution plans) + UI panel.', 'Proactive bottleneck alerts + AI-generated resolution recommendations', '1) Alerting service 2) AI recommender 3) Server actions 4) UI panel 5) Caching')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-013', 'Implement SOP Opportunity Detection', 'Detect Standard Operating Procedure opportunities from recurring successful patterns in the process graph.', 'not_started', 'p2', 'Sprint 12', '2026-06-18', '2026-06-20', 8, 55, 'You are a Senior Full Stack Engineer. Build sop-detector.ts with 4 SOP types: standard_procedure, decision_template, communication_template, avoidance_rule.', 'Detect SOP opportunities from recurring successful patterns in the process graph', '1) sop-detector.ts 2) 4 SOP types 3) frequency/evidence/impact/confidence 4) Server action 5) TypeScript types')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-014', 'Build SOP Draft Generation Service', 'AI-powered SOP draft generation: title, purpose, scope, steps, acceptance criteria, exceptions.', 'not_started', 'p2', 'Sprint 12', '2026-06-20', '2026-06-23', 8, 56, 'You are a Senior Full Stack Engineer. Build sop-generator.ts (OpenAI GPT-4o structured SOP drafts) + sop-draft-dialog.tsx (view/edit/save as Document).', 'Generate AI-drafted SOPs from detected opportunities, editable by users before saving', '1) sop-generator.ts 2) Structured SOP output 3) Server action 4) UI dialog 5) Save as Document 6) i18n')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-015', 'Design Retrospective Data Model & Triggers', 'Design retrospectives table schema and generation triggers (milestone completion + on-demand).', 'not_started', 'p2', 'Sprint 12', '2026-06-17', '2026-06-18', 4, 57, 'You are a Senior Data Architect. Design retrospectives table with narrative, patterns, bottlenecks, SOPs, metrics, action_items. Triggers on milestone completion + on-demand.', 'Design retrospectives table schema and generation triggers (milestone completion + on-demand)', '1) Data model documented 2) Migration file 3) Auto trigger on completion 4) On-demand trigger 5) TypeScript types 6) Action contract')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-016', 'Implement AI Retrospective Generation', 'Generate comprehensive AI retrospectives from timeline, patterns, bottlenecks, and metrics.', 'not_started', 'p2', 'Sprint 12', '2026-06-20', '2026-06-23', 10, 58, 'You are a Senior Full Stack Engineer. Build retrospective-generator.ts: gather timeline/patterns/bottlenecks/SOPs, compute metrics, generate 5-section narrative via OpenAI.', 'Generate comprehensive AI retrospectives from timeline, patterns, bottlenecks, and metrics', '1) retrospective-generator.ts 2) Data gathering 3) Key metrics 4) 5-section narrative 5) Server action 6) Embedding integration 7) Caching')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-017', 'Build Retrospective UI & Export', 'Retrospective viewing UI with sections, metrics, action items, and PDF/Markdown export.', 'not_started', 'p3', 'Sprint 12', '2026-06-23', '2026-06-25', 8, 59, 'You are a Senior Frontend Engineer. Build retrospective list page, detail view with 5 sections, action items promotion, PDF export (print CSS), Markdown export.', 'Retrospective viewing UI with sections, metrics, action items, and PDF/Markdown export', '1) List page 2) Detail view 3) Action items promotion 4) PDF export 5) Markdown export 6) i18n 7) Integrated')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-018', 'Implement Improvement Backlog Item Creation', 'Auto-generate improvement backlog items from bottlenecks, SOPs, deviations, and retrospective actions.', 'not_started', 'p2', 'Sprint 12', '2026-06-20', '2026-06-23', 8, 60, 'You are a Senior Full Stack Engineer. Build improvement-creator.ts with 4 creation functions. Items stored as roadmap_tasks with sprint_name=Improvement Backlog.', 'Auto-generate improvement backlog items from bottlenecks, SOPs, deviations, and retrospective actions', '1) improvement-creator.ts 2) 4 creation functions 3) Priority mapping 4) Server action 5) Batch creation 6) Deduplication')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-019', 'Build Improvement Backlog UI & Roadmap Integration', 'Improvement backlog view with source badges, priority filter, and one-click promotion to roadmap.', 'not_started', 'p2', 'Sprint 12', '2026-06-23', '2026-06-25', 8, 61, 'You are a Senior Frontend Engineer. Build improvement backlog page, improvement-backlog.tsx with source badges, promote-dialog.tsx, promoteToRoadmapAction.', 'Improvement backlog view with source badges, priority filter, and one-click promotion to roadmap', '1) Backlog page 2) Source badges 3) TaskFormDialog edit 4) Promote to Roadmap 5) Server action 6) i18n')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-020', 'Design Insight-to-Action Approval Workflow', 'Design the workflow for converting process insights into user-approved actions with 5 approval states.', 'not_started', 'p1', 'Sprint 12', '2026-06-20', '2026-06-21', 4, 62, 'You are a Senior Product Engineer. Design insight-to-action workflow: 5 states (pending_review, approved, modified, rejected, enacted), insight_actions table, UI flow, notification badge.', 'Design approval workflow for converting process insights into user-approved actions', '1) Workflow document 2) 5 approval states 3) insight_actions table 4) TypeScript types 5) Action contracts')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-021', 'Implement Action Generation from Process Insights', 'Generate AI-proposed actions from insights with confidence, impact, effort, and risk estimates.', 'not_started', 'p2', 'Sprint 12', '2026-06-23', '2026-06-25', 10, 63, 'You are a Senior Full Stack Engineer. Build action-generator.ts with 4 generation functions, ProposedAction type (confidence, impact, effort, risk), batch processing, deduplication.', 'Generate AI-proposed actions from insights with confidence, impact, effort, and risk estimates', '1) action-generator.ts 2) ProposedAction type 3) Batch generation 4) Server action 5) Deduplication 6) insight_actions stored')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

INSERT INTO roadmap_tasks (organization_id, project_id, milestone_id, external_key, title, description, status, priority, sprint_name, start_date, end_date, estimate_hours, order_index, prompt_body, prompt_context, acceptance_criteria)
VALUES ('4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', 'a1b2c3d4-0001-4000-8000-000000000012', 'PI-022', 'Build Insight-to-Action UI with Approval Flow', 'UI for reviewing AI-proposed actions: approve, modify, or reject with auto task creation.', 'not_started', 'p2', 'Sprint 12', '2026-06-25', '2026-06-27', 10, 64, 'You are a Senior Frontend Engineer. Build insight review page with 3 tabs, insight-action-card.tsx (confidence, impact, effort, risk), reject-dialog.tsx, approve/modify/reject server actions, notification badge.', 'UI for reviewing AI-proposed actions: approve, modify, or reject with auto task creation', '1) Review page 3 tabs 2) Action cards 3) Approve flow 4) Modify flow 5) Reject flow 6) Server actions 7) i18n 8) Notification badge')
ON CONFLICT (project_id, external_key) WHERE external_key IS NOT NULL AND deleted_at IS NULL DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, status=EXCLUDED.status, priority=EXCLUDED.priority, milestone_id=EXCLUDED.milestone_id, estimate_hours=EXCLUDED.estimate_hours, prompt_body=EXCLUDED.prompt_body, prompt_context=EXCLUDED.prompt_context, acceptance_criteria=EXCLUDED.acceptance_criteria, updated_at=now();

-- ═══════════════════════════════════════════════════════════════════════════════
-- STEP 3: Insert Dependencies (finish_to_start)
-- Uses task external_keys to resolve UUIDs
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO task_dependencies (organization_id, project_id, predecessor_id, successor_id, dependency_type)
SELECT '4f00f16b-96d8-4fd6-9375-20e2b11564a6', 'a30e3eb9-528e-46ce-b6d6-9ed80086b936', p.id, s.id, 'finish_to_start'
FROM roadmap_tasks p, roadmap_tasks s
WHERE p.project_id = 'a30e3eb9-528e-46ce-b6d6-9ed80086b936'
  AND s.project_id = 'a30e3eb9-528e-46ce-b6d6-9ed80086b936'
  AND p.deleted_at IS NULL AND s.deleted_at IS NULL
  AND (p.external_key, s.external_key) IN (
    ('PI-001', 'PI-002'), ('PI-002', 'PI-003'), ('PI-002', 'PI-004'),
    ('PI-003', 'PI-005'), ('PI-004', 'PI-005'), ('PI-001', 'PI-006'),
    ('PI-006', 'PI-007'), ('PI-006', 'PI-008'), ('PI-007', 'PI-009'),
    ('PI-008', 'PI-009'), ('PI-008', 'PI-010'), ('PI-010', 'PI-011'),
    ('PI-011', 'PI-012'), ('PI-008', 'PI-013'), ('PI-013', 'PI-014'),
    ('PI-007', 'PI-015'), ('PI-015', 'PI-016'), ('PI-016', 'PI-017'),
    ('PI-010', 'PI-018'), ('PI-013', 'PI-018'), ('PI-018', 'PI-019'),
    ('PI-012', 'PI-020'), ('PI-018', 'PI-020'), ('PI-020', 'PI-021'),
    ('PI-021', 'PI-022')
  )
ON CONFLICT (predecessor_id, successor_id, dependency_type) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════════
-- VERIFICATION
-- ═══════════════════════════════════════════════════════════════════════════════
-- SELECT count(*) as task_count FROM roadmap_tasks
-- WHERE project_id = 'a30e3eb9-528e-46ce-b6d6-9ed80086b936' AND external_key LIKE 'PI-%' AND deleted_at IS NULL;
-- Expected: 22
--
-- SELECT count(*) as dep_count FROM task_dependencies
-- WHERE project_id = 'a30e3eb9-528e-46ce-b6d6-9ed80086b936';
-- Expected: 25