// ============================================================================
// ProjectOps360° — Isabella Root Cause · formatter (pure, bilingual)
// ============================================================================
// ISABELLA-ROOT-CAUSE-CONSTRAINT-ANALYSIS-ENGINE
//
// Concise Isabella answer: classified findings + confidence + evidence-chain
// summary + limitations, and an explicit note that recommendations belong to the
// next engine. Never an action plan. Pure, locale-aware (inline convention).
// ============================================================================

import type { IsabellaRootCauseAnalysis, RootCauseClassification, RootCauseLanguage } from "./types";

const CLASS_LABEL: Record<RootCauseClassification, { en: string; es: string }> = {
  confirmed_cause: { en: "Confirmed cause", es: "Causa confirmada" },
  likely_cause: { en: "Likely cause", es: "Causa probable" },
  possible_cause: { en: "Possible cause", es: "Causa posible" },
  insufficient_evidence: { en: "Insufficient evidence", es: "Evidencia insuficiente" },
};

export function classificationLabel(c: RootCauseClassification, language: RootCauseLanguage): string {
  return CLASS_LABEL[c][language === "es" ? "es" : "en"];
}

/** Concise, evidence-backed root-cause analysis text for Isabella. */
export function formatRootCauseAnalysisForIsabella(analysis: IsabellaRootCauseAnalysis, language: RootCauseLanguage): string {
  const es = language === "es";
  const title = es ? "Análisis de causa raíz" : "Root Cause Analysis";

  if (analysis.status !== "ready" && analysis.status !== "partial") {
    return `**${title}**\n\n${analysis.message ?? analysis.summary}`;
  }

  const parts: string[] = [
    `**${title}**`,
    "",
    `${es ? "Confianza" : "Confidence"}: ${analysis.confidence}`,
    "",
    `${es ? "Resumen" : "Summary"}: ${analysis.summary}`,
  ];

  if (analysis.findings.length > 0) {
    parts.push("", `**${es ? "Hallazgos" : "Findings"}**`);
    analysis.findings.slice(0, 8).forEach((f, i) => {
      parts.push(`${i + 1}. ${classificationLabel(f.classification, language)}: ${f.label} — ${f.confidence}`);
      parts.push(`   ${f.explanation}`);
      for (const l of (f.limitations ?? []).slice(0, 2)) parts.push(`   · ${es ? "Limitación" : "Limitation"}: ${l}`);
    });
  }

  if (analysis.investigationGaps.length > 0) {
    parts.push("", `**${es ? "Gaps de investigación" : "Investigation gaps"}**`);
    for (const g of analysis.investigationGaps.slice(0, 6)) parts.push(`- ${g.label}`);
  }

  parts.push("", es ? "Fuente: datos verificados del proyecto actual." : "Source: verified project data.");
  parts.push(es ? "Nota: las recomendaciones se generarán en el siguiente motor." : "Note: recommendations will be generated by the next engine.");
  return parts.join("\n");
}
