// ============================================================================
// ProjectOps360° — generate the Product Brain knowledge seed migration
// ============================================================================
// Emits supabase/migrations/20260817000000_knowledge_product_brain.sql from the
// curated manifest (src/lib/knowledge-os/seeds/product-brain-knowledge.ts) so
// the DB seed and the typed source of truth never drift.
//
// Run: node --experimental-strip-types scripts/generate-knowledge-seed-sql.ts
// ============================================================================

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PRODUCT_BRAIN_PACKAGES } from "../src/lib/knowledge-os/seeds/product-brain-knowledge.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "supabase", "migrations", "20260817000000_knowledge_product_brain.sql");

/** SQL single-quote escape. */
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const pkgRows = PRODUCT_BRAIN_PACKAGES.map(
  (p) => `    (NULL, ${q(p.slug)}, ${q(p.domain)}, 'published', 'en')`,
).join(",\n");

const verRows = PRODUCT_BRAIN_PACKAGES.map((p) => `    (${q(p.slug)}, ${q(p.tier)}, ${q(p.sourceRef)})`).join(
  ",\n",
);

const locRows = PRODUCT_BRAIN_PACKAGES.flatMap((p) => [
  `    (${q(p.slug)}, 'en', ${q(p.en.title)}, ${q(p.en.body)})`,
  `    (${q(p.slug)}, 'es', ${q(p.es.title)}, ${q(p.es.body)})`,
]).join(",\n");

const sql = `-- ============================================================================
-- ProjectOps360° — Dr. Isabella: Product Brain knowledge corpus (GENERATED)
-- ============================================================================
-- GENERATED by scripts/generate-knowledge-seed-sql.ts from the curated manifest
-- src/lib/knowledge-os/seeds/product-brain-knowledge.ts. Do NOT edit by hand —
-- edit the manifest and regenerate.
--
-- Seeds the curated Product Intelligence knowledge packages so Isabella retrieves
-- ProjectOps360° product facts (Living Graph, Critical Path, blocked vs waiting,
-- ProjectOps Scribe, Project Memory, Variance/Timeline/What-if, Resource Capacity,
-- REG-008/009/010, Execution Status Engine) from the SAME hybrid corpus as the
-- existing People & Permissions packages. Idempotent (ON CONFLICT DO NOTHING).
-- Chunks are derived (one per localization); embeddings are filled by the
-- existing indexer (lexical search works immediately).
-- ============================================================================

WITH pkg AS (
  INSERT INTO public.knowledge_packages (organization_id, slug, domain, status, default_language)
  VALUES
${pkgRows}
  ON CONFLICT DO NOTHING
  RETURNING id, slug
),
ver AS (
  INSERT INTO public.knowledge_package_versions (package_id, organization_id, version_no, is_current, confidence_tier, source_refs)
  SELECT p.id, NULL, 1, true, t.tier, jsonb_build_array(t.source_ref)
  FROM pkg p
  JOIN (VALUES
${verRows}
  ) AS t(slug, tier, source_ref) ON t.slug = p.slug
  RETURNING id, package_id
),
loc AS (
  INSERT INTO public.knowledge_localizations (version_id, package_id, organization_id, language, title, body)
  SELECT v.id, v.package_id, NULL, c.language, c.title, c.body
  FROM ver v
  JOIN pkg p ON p.id = v.package_id
  JOIN (VALUES
${locRows}
  ) AS c(slug, language, title, body) ON c.slug = p.slug
  RETURNING id, version_id, package_id, organization_id, language, body
)
INSERT INTO public.knowledge_chunks (
  localization_id, version_id, package_id, organization_id, language,
  ordinal, body, content_hash, index_status
)
SELECT
  l.id, l.version_id, l.package_id, l.organization_id, l.language,
  0, l.body, encode(digest(l.body, 'sha256'), 'hex'), 'pending'
FROM loc l;
`;

writeFileSync(OUT, sql, "utf8");
console.log(`[knowledge-seed] wrote ${PRODUCT_BRAIN_PACKAGES.length} packages → ${OUT}`);
